// Code generated by MockGen. DO NOT EDIT.
// Source: room.go
//
// Generated by this command:
//
//	mockgen -source=room.go -destination=mocks/room_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/kirillveshnyakov/go-room-booking-service/room-booking-service/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockroomRepository is a mock of roomRepository interface.
type MockroomRepository struct {
	ctrl     *gomock.Controller
	recorder *MockroomRepositoryMockRecorder
	isgomock struct{}
}

// MockroomRepositoryMockRecorder is the mock recorder for MockroomRepository.
type MockroomRepositoryMockRecorder struct {
	mock *MockroomRepository
}

// NewMockroomRepository creates a new mock instance.
func NewMockroomRepository(ctrl *gomock.Controller) *MockroomRepository {
	mock := &MockroomRepository{ctrl: ctrl}
	mock.recorder = &MockroomRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockroomRepository) EXPECT() *MockroomRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockroomRepository) Create(ctx context.Context, room entity.Room) (entity.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, room)
	ret0, _ := ret[0].(entity.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockroomRepositoryMockRecorder) Create(ctx, room any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockroomRepository)(nil).Create), ctx, room)
}

// List mocks base method.
func (m *MockroomRepository) List(ctx context.Context) ([]entity.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]entity.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockroomRepositoryMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockroomRepository)(nil).List), ctx)
}
