// Code generated by MockGen. DO NOT EDIT.
// Source: auth.go
//
// Generated by this command:
//
//	mockgen -source=auth.go -destination=mocks/auth_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	entity "github.com/kirillveshnyakov/go-room-booking-service/room-booking-service/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockuserRepository is a mock of userRepository interface.
type MockuserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockuserRepositoryMockRecorder
	isgomock struct{}
}

// MockuserRepositoryMockRecorder is the mock recorder for MockuserRepository.
type MockuserRepositoryMockRecorder struct {
	mock *MockuserRepository
}

// NewMockuserRepository creates a new mock instance.
func NewMockuserRepository(ctrl *gomock.Controller) *MockuserRepository {
	mock := &MockuserRepository{ctrl: ctrl}
	mock.recorder = &MockuserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserRepository) EXPECT() *MockuserRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockuserRepository) Create(ctx context.Context, email string, role entity.UserRole, passwordHash string) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, email, role, passwordHash)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockuserRepositoryMockRecorder) Create(ctx, email, role, passwordHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockuserRepository)(nil).Create), ctx, email, role, passwordHash)
}

// GetByEmail mocks base method.
func (m *MockuserRepository) GetByEmail(ctx context.Context, email string) (entity.AuthUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(entity.AuthUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockuserRepositoryMockRecorder) GetByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockuserRepository)(nil).GetByEmail), ctx, email)
}

// GetByID mocks base method.
func (m *MockuserRepository) GetByID(ctx context.Context, userID uuid.UUID) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, userID)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockuserRepositoryMockRecorder) GetByID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockuserRepository)(nil).GetByID), ctx, userID)
}

// MocksessionRepository is a mock of sessionRepository interface.
type MocksessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MocksessionRepositoryMockRecorder
	isgomock struct{}
}

// MocksessionRepositoryMockRecorder is the mock recorder for MocksessionRepository.
type MocksessionRepositoryMockRecorder struct {
	mock *MocksessionRepository
}

// NewMocksessionRepository creates a new mock instance.
func NewMocksessionRepository(ctrl *gomock.Controller) *MocksessionRepository {
	mock := &MocksessionRepository{ctrl: ctrl}
	mock.recorder = &MocksessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksessionRepository) EXPECT() *MocksessionRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MocksessionRepository) Create(ctx context.Context, session entity.Session) (entity.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, session)
	ret0, _ := ret[0].(entity.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MocksessionRepositoryMockRecorder) Create(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MocksessionRepository)(nil).Create), ctx, session)
}

// GetByID mocks base method.
func (m *MocksessionRepository) GetByID(ctx context.Context, sessionID uuid.UUID) (entity.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, sessionID)
	ret0, _ := ret[0].(entity.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MocksessionRepositoryMockRecorder) GetByID(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MocksessionRepository)(nil).GetByID), ctx, sessionID)
}

// Revoke mocks base method.
func (m *MocksessionRepository) Revoke(ctx context.Context, sessionID uuid.UUID, revokedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, sessionID, revokedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revoke indicates an expected call of Revoke.
func (mr *MocksessionRepositoryMockRecorder) Revoke(ctx, sessionID, revokedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MocksessionRepository)(nil).Revoke), ctx, sessionID, revokedAt)
}

// RevokeAllByUser mocks base method.
func (m *MocksessionRepository) RevokeAllByUser(ctx context.Context, userID uuid.UUID, revokedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAllByUser", ctx, userID, revokedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeAllByUser indicates an expected call of RevokeAllByUser.
func (mr *MocksessionRepositoryMockRecorder) RevokeAllByUser(ctx, userID, revokedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAllByUser", reflect.TypeOf((*MocksessionRepository)(nil).RevokeAllByUser), ctx, userID, revokedAt)
}

// RotateRefreshToken mocks base method.
func (m *MocksessionRepository) RotateRefreshToken(ctx context.Context, sessionID uuid.UUID, oldRefreshTokenHash, newRefreshTokenHash []byte) (entity.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RotateRefreshToken", ctx, sessionID, oldRefreshTokenHash, newRefreshTokenHash)
	ret0, _ := ret[0].(entity.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RotateRefreshToken indicates an expected call of RotateRefreshToken.
func (mr *MocksessionRepositoryMockRecorder) RotateRefreshToken(ctx, sessionID, oldRefreshTokenHash, newRefreshTokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RotateRefreshToken", reflect.TypeOf((*MocksessionRepository)(nil).RotateRefreshToken), ctx, sessionID, oldRefreshTokenHash, newRefreshTokenHash)
}

// MockpasswordHasher is a mock of passwordHasher interface.
type MockpasswordHasher struct {
	ctrl     *gomock.Controller
	recorder *MockpasswordHasherMockRecorder
	isgomock struct{}
}

// MockpasswordHasherMockRecorder is the mock recorder for MockpasswordHasher.
type MockpasswordHasherMockRecorder struct {
	mock *MockpasswordHasher
}

// NewMockpasswordHasher creates a new mock instance.
func NewMockpasswordHasher(ctrl *gomock.Controller) *MockpasswordHasher {
	mock := &MockpasswordHasher{ctrl: ctrl}
	mock.recorder = &MockpasswordHasherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpasswordHasher) EXPECT() *MockpasswordHasherMockRecorder {
	return m.recorder
}

// Compare mocks base method.
func (m *MockpasswordHasher) Compare(hash, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compare", hash, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// Compare indicates an expected call of Compare.
func (mr *MockpasswordHasherMockRecorder) Compare(hash, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compare", reflect.TypeOf((*MockpasswordHasher)(nil).Compare), hash, password)
}

// Hash mocks base method.
func (m *MockpasswordHasher) Hash(password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hash", password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Hash indicates an expected call of Hash.
func (mr *MockpasswordHasherMockRecorder) Hash(password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hash", reflect.TypeOf((*MockpasswordHasher)(nil).Hash), password)
}

// MockaccessTokenManager is a mock of accessTokenManager interface.
type MockaccessTokenManager struct {
	ctrl     *gomock.Controller
	recorder *MockaccessTokenManagerMockRecorder
	isgomock struct{}
}

// MockaccessTokenManagerMockRecorder is the mock recorder for MockaccessTokenManager.
type MockaccessTokenManagerMockRecorder struct {
	mock *MockaccessTokenManager
}

// NewMockaccessTokenManager creates a new mock instance.
func NewMockaccessTokenManager(ctrl *gomock.Controller) *MockaccessTokenManager {
	mock := &MockaccessTokenManager{ctrl: ctrl}
	mock.recorder = &MockaccessTokenManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockaccessTokenManager) EXPECT() *MockaccessTokenManagerMockRecorder {
	return m.recorder
}

// CreateAccessToken mocks base method.
func (m *MockaccessTokenManager) CreateAccessToken(identity entity.Identity) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccessToken", identity)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccessToken indicates an expected call of CreateAccessToken.
func (mr *MockaccessTokenManagerMockRecorder) CreateAccessToken(identity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccessToken", reflect.TypeOf((*MockaccessTokenManager)(nil).CreateAccessToken), identity)
}

// MockrefreshTokenManager is a mock of refreshTokenManager interface.
type MockrefreshTokenManager struct {
	ctrl     *gomock.Controller
	recorder *MockrefreshTokenManagerMockRecorder
	isgomock struct{}
}

// MockrefreshTokenManagerMockRecorder is the mock recorder for MockrefreshTokenManager.
type MockrefreshTokenManagerMockRecorder struct {
	mock *MockrefreshTokenManager
}

// NewMockrefreshTokenManager creates a new mock instance.
func NewMockrefreshTokenManager(ctrl *gomock.Controller) *MockrefreshTokenManager {
	mock := &MockrefreshTokenManager{ctrl: ctrl}
	mock.recorder = &MockrefreshTokenManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockrefreshTokenManager) EXPECT() *MockrefreshTokenManagerMockRecorder {
	return m.recorder
}

// CreateRefreshToken mocks base method.
func (m *MockrefreshTokenManager) CreateRefreshToken(sessionID uuid.UUID) (string, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRefreshToken", sessionID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateRefreshToken indicates an expected call of CreateRefreshToken.
func (mr *MockrefreshTokenManagerMockRecorder) CreateRefreshToken(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRefreshToken", reflect.TypeOf((*MockrefreshTokenManager)(nil).CreateRefreshToken), sessionID)
}

// ParseRefreshToken mocks base method.
func (m *MockrefreshTokenManager) ParseRefreshToken(rawToken string) (uuid.UUID, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseRefreshToken", rawToken)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ParseRefreshToken indicates an expected call of ParseRefreshToken.
func (mr *MockrefreshTokenManagerMockRecorder) ParseRefreshToken(rawToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseRefreshToken", reflect.TypeOf((*MockrefreshTokenManager)(nil).ParseRefreshToken), rawToken)
}
