// Code generated by MockGen. DO NOT EDIT.
// Source: schedule.go
//
// Generated by this command:
//
//	mockgen -source=schedule.go -destination=mocks/schedule_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/kirillveshnyakov/go-room-booking-service/room-booking-service/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockscheduleRepository is a mock of scheduleRepository interface.
type MockscheduleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockscheduleRepositoryMockRecorder
	isgomock struct{}
}

// MockscheduleRepositoryMockRecorder is the mock recorder for MockscheduleRepository.
type MockscheduleRepositoryMockRecorder struct {
	mock *MockscheduleRepository
}

// NewMockscheduleRepository creates a new mock instance.
func NewMockscheduleRepository(ctrl *gomock.Controller) *MockscheduleRepository {
	mock := &MockscheduleRepository{ctrl: ctrl}
	mock.recorder = &MockscheduleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockscheduleRepository) EXPECT() *MockscheduleRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockscheduleRepository) Create(ctx context.Context, schedule entity.Schedule) (entity.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, schedule)
	ret0, _ := ret[0].(entity.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockscheduleRepositoryMockRecorder) Create(ctx, schedule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockscheduleRepository)(nil).Create), ctx, schedule)
}
