// Code generated by MockGen. DO NOT EDIT.
// Source: slot.go
//
// Generated by this command:
//
//	mockgen -source=slot.go -destination=mocks/slot_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	entity "github.com/kirillveshnyakov/go-room-booking-service/room-booking-service/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockslotRepository is a mock of slotRepository interface.
type MockslotRepository struct {
	ctrl     *gomock.Controller
	recorder *MockslotRepositoryMockRecorder
	isgomock struct{}
}

// MockslotRepositoryMockRecorder is the mock recorder for MockslotRepository.
type MockslotRepositoryMockRecorder struct {
	mock *MockslotRepository
}

// NewMockslotRepository creates a new mock instance.
func NewMockslotRepository(ctrl *gomock.Controller) *MockslotRepository {
	mock := &MockslotRepository{ctrl: ctrl}
	mock.recorder = &MockslotRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockslotRepository) EXPECT() *MockslotRepositoryMockRecorder {
	return m.recorder
}

// CheckExistsForDate mocks base method.
func (m *MockslotRepository) CheckExistsForDate(ctx context.Context, roomID uuid.UUID, targetDate time.Time) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckExistsForDate", ctx, roomID, targetDate)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckExistsForDate indicates an expected call of CheckExistsForDate.
func (mr *MockslotRepositoryMockRecorder) CheckExistsForDate(ctx, roomID, targetDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckExistsForDate", reflect.TypeOf((*MockslotRepository)(nil).CheckExistsForDate), ctx, roomID, targetDate)
}

// Create mocks base method.
func (m *MockslotRepository) Create(ctx context.Context, roomID uuid.UUID, startAts []time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, roomID, startAts)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockslotRepositoryMockRecorder) Create(ctx, roomID, startAts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockslotRepository)(nil).Create), ctx, roomID, startAts)
}

// ListFree mocks base method.
func (m *MockslotRepository) ListFree(ctx context.Context, roomID uuid.UUID, targetDate time.Time) ([]entity.Slot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFree", ctx, roomID, targetDate)
	ret0, _ := ret[0].([]entity.Slot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFree indicates an expected call of ListFree.
func (mr *MockslotRepositoryMockRecorder) ListFree(ctx, roomID, targetDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFree", reflect.TypeOf((*MockslotRepository)(nil).ListFree), ctx, roomID, targetDate)
}

// MockscheduleRepository is a mock of scheduleRepository interface.
type MockscheduleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockscheduleRepositoryMockRecorder
	isgomock struct{}
}

// MockscheduleRepositoryMockRecorder is the mock recorder for MockscheduleRepository.
type MockscheduleRepositoryMockRecorder struct {
	mock *MockscheduleRepository
}

// NewMockscheduleRepository creates a new mock instance.
func NewMockscheduleRepository(ctrl *gomock.Controller) *MockscheduleRepository {
	mock := &MockscheduleRepository{ctrl: ctrl}
	mock.recorder = &MockscheduleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockscheduleRepository) EXPECT() *MockscheduleRepositoryMockRecorder {
	return m.recorder
}

// GetRuleForDay mocks base method.
func (m *MockscheduleRepository) GetRuleForDay(ctx context.Context, roomID uuid.UUID, dayOfWeek entity.DayOfWeek) (entity.ScheduleRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRuleForDay", ctx, roomID, dayOfWeek)
	ret0, _ := ret[0].(entity.ScheduleRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRuleForDay indicates an expected call of GetRuleForDay.
func (mr *MockscheduleRepositoryMockRecorder) GetRuleForDay(ctx, roomID, dayOfWeek any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRuleForDay", reflect.TypeOf((*MockscheduleRepository)(nil).GetRuleForDay), ctx, roomID, dayOfWeek)
}

// MockroomRepository is a mock of roomRepository interface.
type MockroomRepository struct {
	ctrl     *gomock.Controller
	recorder *MockroomRepositoryMockRecorder
	isgomock struct{}
}

// MockroomRepositoryMockRecorder is the mock recorder for MockroomRepository.
type MockroomRepositoryMockRecorder struct {
	mock *MockroomRepository
}

// NewMockroomRepository creates a new mock instance.
func NewMockroomRepository(ctrl *gomock.Controller) *MockroomRepository {
	mock := &MockroomRepository{ctrl: ctrl}
	mock.recorder = &MockroomRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockroomRepository) EXPECT() *MockroomRepositoryMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockroomRepository) GetByID(ctx context.Context, roomID uuid.UUID) (entity.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, roomID)
	ret0, _ := ret[0].(entity.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockroomRepositoryMockRecorder) GetByID(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockroomRepository)(nil).GetByID), ctx, roomID)
}
