// Code generated by MockGen. DO NOT EDIT.
// Source: booking.go
//
// Generated by this command:
//
//	mockgen -source=booking.go -destination=mocks/booking_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/kirillveshnyakov/go-room-booking-service/room-booking-service/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockbookingRepository is a mock of bookingRepository interface.
type MockbookingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockbookingRepositoryMockRecorder
	isgomock struct{}
}

// MockbookingRepositoryMockRecorder is the mock recorder for MockbookingRepository.
type MockbookingRepositoryMockRecorder struct {
	mock *MockbookingRepository
}

// NewMockbookingRepository creates a new mock instance.
func NewMockbookingRepository(ctrl *gomock.Controller) *MockbookingRepository {
	mock := &MockbookingRepository{ctrl: ctrl}
	mock.recorder = &MockbookingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockbookingRepository) EXPECT() *MockbookingRepositoryMockRecorder {
	return m.recorder
}

// Cancel mocks base method.
func (m *MockbookingRepository) Cancel(ctx context.Context, bookingID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cancel", ctx, bookingID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Cancel indicates an expected call of Cancel.
func (mr *MockbookingRepositoryMockRecorder) Cancel(ctx, bookingID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockbookingRepository)(nil).Cancel), ctx, bookingID)
}

// Create mocks base method.
func (m *MockbookingRepository) Create(ctx context.Context, slotID, userID uuid.UUID, conferenceLink string) (entity.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, slotID, userID, conferenceLink)
	ret0, _ := ret[0].(entity.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockbookingRepositoryMockRecorder) Create(ctx, slotID, userID, conferenceLink any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockbookingRepository)(nil).Create), ctx, slotID, userID, conferenceLink)
}

// GetByID mocks base method.
func (m *MockbookingRepository) GetByID(ctx context.Context, bookingID uuid.UUID) (entity.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, bookingID)
	ret0, _ := ret[0].(entity.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockbookingRepositoryMockRecorder) GetByID(ctx, bookingID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockbookingRepository)(nil).GetByID), ctx, bookingID)
}

// List mocks base method.
func (m *MockbookingRepository) List(ctx context.Context, pageLimit, pageOffset int) ([]entity.Booking, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, pageLimit, pageOffset)
	ret0, _ := ret[0].([]entity.Booking)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockbookingRepositoryMockRecorder) List(ctx, pageLimit, pageOffset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockbookingRepository)(nil).List), ctx, pageLimit, pageOffset)
}

// ListByUser mocks base method.
func (m *MockbookingRepository) ListByUser(ctx context.Context, userID uuid.UUID) ([]entity.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID)
	ret0, _ := ret[0].([]entity.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockbookingRepositoryMockRecorder) ListByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockbookingRepository)(nil).ListByUser), ctx, userID)
}

// MockconferenceLinkGenerator is a mock of conferenceLinkGenerator interface.
type MockconferenceLinkGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockconferenceLinkGeneratorMockRecorder
	isgomock struct{}
}

// MockconferenceLinkGeneratorMockRecorder is the mock recorder for MockconferenceLinkGenerator.
type MockconferenceLinkGeneratorMockRecorder struct {
	mock *MockconferenceLinkGenerator
}

// NewMockconferenceLinkGenerator creates a new mock instance.
func NewMockconferenceLinkGenerator(ctrl *gomock.Controller) *MockconferenceLinkGenerator {
	mock := &MockconferenceLinkGenerator{ctrl: ctrl}
	mock.recorder = &MockconferenceLinkGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockconferenceLinkGenerator) EXPECT() *MockconferenceLinkGeneratorMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockconferenceLinkGenerator) Generate(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockconferenceLinkGeneratorMockRecorder) Generate(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockconferenceLinkGenerator)(nil).Generate), ctx)
}
