// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: booking.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelBooking = `-- name: CancelBooking :execrows
UPDATE bookings
SET status = 'cancelled'
WHERE id = $1
`

func (q *Queries) CancelBooking(ctx context.Context, bookingID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, cancelBooking, bookingID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countBookings = `-- name: CountBookings :one
SELECT COUNT(*) AS total
FROM bookings
`

func (q *Queries) CountBookings(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countBookings)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (slot_id,
                      user_id,
                      conference_link)
SELECT s.id,
       $1,
       $2
FROM slots AS s
WHERE s.id = $3
  AND s.start_at >= NOW()
RETURNING
    id,
    slot_id,
    user_id,
    status,
    conference_link,
    created_at
`

type CreateBookingParams struct {
	UserID         uuid.UUID
	ConferenceLink pgtype.Text
	SlotID         uuid.UUID
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, createBooking, arg.UserID, arg.ConferenceLink, arg.SlotID)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.SlotID,
		&i.UserID,
		&i.Status,
		&i.ConferenceLink,
		&i.CreatedAt,
	)
	return i, err
}

const getBookingByID = `-- name: GetBookingByID :one
SELECT id,
       slot_id,
       user_id,
       status,
       conference_link,
       created_at
FROM bookings
WHERE id = $1
`

func (q *Queries) GetBookingByID(ctx context.Context, bookingID uuid.UUID) (Booking, error) {
	row := q.db.QueryRow(ctx, getBookingByID, bookingID)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.SlotID,
		&i.UserID,
		&i.Status,
		&i.ConferenceLink,
		&i.CreatedAt,
	)
	return i, err
}

const listBookings = `-- name: ListBookings :many
SELECT id,
       slot_id,
       user_id,
       status,
       conference_link,
       created_at
FROM bookings
ORDER BY created_at DESC, id DESC
LIMIT $2
OFFSET $1
`

type ListBookingsParams struct {
	PageOffset int32
	PageLimit  int32
}

func (q *Queries) ListBookings(ctx context.Context, arg ListBookingsParams) ([]Booking, error) {
	rows, err := q.db.Query(ctx, listBookings, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Booking{}
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.SlotID,
			&i.UserID,
			&i.Status,
			&i.ConferenceLink,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserFutureBookings = `-- name: ListUserFutureBookings :many
SELECT b.id,
       b.slot_id,
       b.user_id,
       b.status,
       b.conference_link,
       b.created_at
FROM bookings AS b
         JOIN slots AS s
              ON b.slot_id = s.id
WHERE b.user_id = $1
  AND s.start_at >= NOW()
ORDER BY s.start_at, b.id
`

func (q *Queries) ListUserFutureBookings(ctx context.Context, userID uuid.UUID) ([]Booking, error) {
	rows, err := q.db.Query(ctx, listUserFutureBookings, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Booking{}
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.SlotID,
			&i.UserID,
			&i.Status,
			&i.ConferenceLink,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
