// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schedule.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSchedule = `-- name: CreateSchedule :one
INSERT INTO schedules (room_id)
VALUES ($1)
RETURNING
    id,
    room_id,
    created_at
`

func (q *Queries) CreateSchedule(ctx context.Context, roomID uuid.UUID) (Schedule, error) {
	row := q.db.QueryRow(ctx, createSchedule, roomID)
	var i Schedule
	err := row.Scan(&i.ID, &i.RoomID, &i.CreatedAt)
	return i, err
}

const createScheduleRule = `-- name: CreateScheduleRule :exec
INSERT INTO schedule_rules (schedule_id, day_of_week, start_at, end_at)
VALUES ($1,
        $2,
        $3,
        $4)
`

type CreateScheduleRuleParams struct {
	ScheduleID uuid.UUID
	DayOfWeek  int32
	StartAt    pgtype.Time
	EndAt      pgtype.Time
}

func (q *Queries) CreateScheduleRule(ctx context.Context, arg CreateScheduleRuleParams) error {
	_, err := q.db.Exec(ctx, createScheduleRule,
		arg.ScheduleID,
		arg.DayOfWeek,
		arg.StartAt,
		arg.EndAt,
	)
	return err
}

const getScheduleRuleForDay = `-- name: GetScheduleRuleForDay :one
SELECT s.id AS schedule_id,
       sr.day_of_week,
       sr.start_at,
       sr.end_at
FROM schedules AS s
         LEFT JOIN schedule_rules AS sr
                   ON sr.schedule_id = s.id
                       AND sr.day_of_week = $1
WHERE s.room_id = $2
`

type GetScheduleRuleForDayParams struct {
	DayOfWeek int32
	RoomID    uuid.UUID
}

type GetScheduleRuleForDayRow struct {
	ScheduleID uuid.UUID
	DayOfWeek  pgtype.Int4
	StartAt    pgtype.Time
	EndAt      pgtype.Time
}

func (q *Queries) GetScheduleRuleForDay(ctx context.Context, arg GetScheduleRuleForDayParams) (GetScheduleRuleForDayRow, error) {
	row := q.db.QueryRow(ctx, getScheduleRuleForDay, arg.DayOfWeek, arg.RoomID)
	var i GetScheduleRuleForDayRow
	err := row.Scan(
		&i.ScheduleID,
		&i.DayOfWeek,
		&i.StartAt,
		&i.EndAt,
	)
	return i, err
}
