// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, refresh_token_hash, expires_at)
VALUES ($1,
        $2,
        $3)
RETURNING
    id,
    user_id,
    refresh_token_hash,
    expires_at,
    revoked_at,
    created_at,
    updated_at
`

type CreateSessionParams struct {
	UserID           uuid.UUID
	RefreshTokenHash []byte
	ExpiresAt        pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.UserID, arg.RefreshTokenHash, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getByID = `-- name: GetByID :one
SELECT id, user_id, refresh_token_hash, expires_at, revoked_at, created_at, updated_at
FROM sessions
WHERE id = $1
`

func (q *Queries) GetByID(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revoke = `-- name: Revoke :exec
UPDATE sessions
SET revoked_at = $1
WHERE id = $2
  AND revoked_at IS NULL
`

type RevokeParams struct {
	RevokedAt pgtype.Timestamptz
	ID        uuid.UUID
}

func (q *Queries) Revoke(ctx context.Context, arg RevokeParams) error {
	_, err := q.db.Exec(ctx, revoke, arg.RevokedAt, arg.ID)
	return err
}

const revokeAllByUser = `-- name: RevokeAllByUser :exec
UPDATE sessions
SET revoked_at = $1
WHERE user_id = $2
  AND revoked_at IS NULL
`

type RevokeAllByUserParams struct {
	RevokedAt pgtype.Timestamptz
	UserID    uuid.UUID
}

func (q *Queries) RevokeAllByUser(ctx context.Context, arg RevokeAllByUserParams) error {
	_, err := q.db.Exec(ctx, revokeAllByUser, arg.RevokedAt, arg.UserID)
	return err
}

const rotateRefreshToken = `-- name: RotateRefreshToken :one
UPDATE sessions
SET refresh_token_hash = $1
WHERE id = $2
  AND refresh_token_hash = $3
  AND revoked_at IS NULL
  AND expires_at > NOW()
RETURNING
    id,
    user_id,
    refresh_token_hash,
    expires_at,
    revoked_at,
    created_at,
    updated_at
`

type RotateRefreshTokenParams struct {
	NewRefreshTokenHash []byte
	ID                  uuid.UUID
	OldRefreshTokenHash []byte
}

func (q *Queries) RotateRefreshToken(ctx context.Context, arg RotateRefreshTokenParams) (Session, error) {
	row := q.db.QueryRow(ctx, rotateRefreshToken, arg.NewRefreshTokenHash, arg.ID, arg.OldRefreshTokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
