// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: slot.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkSlotsExistsForDate = `-- name: CheckSlotsExistsForDate :one
SELECT EXISTS (SELECT 1
               FROM slots AS s
               WHERE s.room_id = $1
                 AND s.start_at >= ($2::date::timestamp AT TIME ZONE 'UTC')
                 AND s.start_at < (($2::date + 1)::timestamp AT TIME ZONE 'UTC'))
`

type CheckSlotsExistsForDateParams struct {
	RoomID     uuid.UUID
	TargetDate pgtype.Date
}

func (q *Queries) CheckSlotsExistsForDate(ctx context.Context, arg CheckSlotsExistsForDateParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkSlotsExistsForDate, arg.RoomID, arg.TargetDate)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createSlotsForDate = `-- name: CreateSlotsForDate :execrows
INSERT INTO slots (room_id,
                   start_at,
                   end_at)
SELECT $1,
       generated_slot.start_at,
       generated_slot.start_at + INTERVAL '30 minutes'
FROM unnest(
             $2::timestamptz[]
     ) AS generated_slot(start_at)
ON CONFLICT (room_id, start_at)
    DO NOTHING
`

type CreateSlotsForDateParams struct {
	RoomID   uuid.UUID
	StartAts []pgtype.Timestamptz
}

func (q *Queries) CreateSlotsForDate(ctx context.Context, arg CreateSlotsForDateParams) (int64, error) {
	result, err := q.db.Exec(ctx, createSlotsForDate, arg.RoomID, arg.StartAts)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSlotByID = `-- name: GetSlotByID :one
SELECT id, room_id, start_at, end_at
FROM slots
WHERE id = $1
`

func (q *Queries) GetSlotByID(ctx context.Context, slotID uuid.UUID) (Slot, error) {
	row := q.db.QueryRow(ctx, getSlotByID, slotID)
	var i Slot
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.StartAt,
		&i.EndAt,
	)
	return i, err
}

const listFreeSlots = `-- name: ListFreeSlots :many
WITH requested_date AS (SELECT $2::date AS value)
SELECT s.id, s.room_id, s.start_at, s.end_at
FROM slots AS s
         CROSS JOIN requested_date AS rd
WHERE s.room_id = $1
  AND s.start_at >= (rd.value::timestamp AT TIME ZONE 'UTC')
  AND s.start_at < ((rd.value + 1)::timestamp AT TIME ZONE 'UTC')
  AND s.start_at > NOW()
  AND NOT EXISTS (SELECT 1
                  FROM bookings AS b
                  WHERE b.slot_id = s.id
                    AND b.status = 'active')
ORDER BY s.start_at, s.id
`

type ListFreeSlotsParams struct {
	RoomID     uuid.UUID
	TargetDate pgtype.Date
}

func (q *Queries) ListFreeSlots(ctx context.Context, arg ListFreeSlotsParams) ([]Slot, error) {
	rows, err := q.db.Query(ctx, listFreeSlots, arg.RoomID, arg.TargetDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Slot{}
	for rows.Next() {
		var i Slot
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.StartAt,
			&i.EndAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
